version: "3"

services:
  # Ваш существующий сервис для тестов (для локального запуска)
  test_runner:
    build: .
    image: java_api_tests
    container_name: java_runner_work
    volumes:
      - .:/tests/
      - maven_repo:/root/.m2 # Кэшируем зависимости Maven

  # Добавляем Jenkins для автоматизации
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_master
    user: root # Нужно для доступа к docker.sock
    ports:
      - "8080:8080" # Интерфейс Jenkins
      - "50000:50000" # Порт для агентов
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
      - ./init-allure.groovy:/var/jenkins_home/init.groovy.d/init-allure.groovy:ro # Пробрасываем скрипт напрямую
      - maven_repo:/root/.m2
    restart: always

volumes:
  jenkins_home:
  maven_repo: