version: "3"

services:
  # Наш основной Jenkins, в котором уже есть Java, Maven и Allure
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_master
    user: root # Важно для работы с томами и системными папками
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/workspace # Наш проект сразу в Jenkins
    restart: always

volumes:
  jenkins_home:
